import './globals.css'
import { Inter } from 'next/font/google'

import HeaderMain from '@/data/components/layout/HeaderMain'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        {/* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.4.0/styles/github-dark.min.css"></link> */}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/stackoverflow-dark.min.css" integrity="sha512-Xn1b0y/BrCD7usnEh6r9CcKxHXFVleVUjGDnfc95zDDwFUwtOz3lJC/XtJcuLRNyrMQJEEToFfwjC9Ue/aWY/g==" crossOrigin="anonymous" referrerPolicy="no-referrer" />        
        {/* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/tokyo-night-dark.min.css" integrity="sha512-dSQLLtgaq2iGigmy9xowRshaMzUHeiIUTvJW/SkUpb1J+ImXOPNGAI7ZC8V5/PiN/XN83B8uIk4qET7AMhdC5Q==" crossOrigin="anonymous" referrerPolicy="no-referrer" /> */}
        {/* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/base16/chalk.min.css" integrity="sha512-mZ09yr+02buuTpmcErRQHzPChzn3AvNo5P7SW1N40psU+HTnw3IeD0tEQdUwU8b6tD2I6mC8eY3vAsYYebKSxw==" crossOrigin="anonymous" referrerPolicy="no-referrer" /> */}
        {/* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/base16/classic-dark.min.css" integrity="sha512-/i5PxfiKXQXfC0IbVgeHpFvVJbCJVXwJ+m4lqagqLPyi0t5yGfVGA9vLAfXnOIar6GmvlxCv22piAaEJOjyNnw==" crossOrigin="anonymous" referrerPolicy="no-referrer" /> */}
        {/* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/base16/edge-dark.min.css" integrity="sha512-15NJjpXlk/UmScfxdrqZP9/1ThMhFG0OHme4LdvmsdiVQs6DaWkpXZws2nkCtaMJsucfQK/RGfm7Pwe29fHAyg==" crossOrigin="anonymous" referrerPolicy="no-referrer" /> */}
        {/* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/base16/eighties.min.css" integrity="sha512-Qo0Vl2GlwHUTIFUL9zn4NzdQb0H9QMnvlUct4b6YzJWB+86XED/2hTb2OSAb8ZysowjH+5VMf0xKVBZWOYTW8w==" crossOrigin="anonymous" referrerPolicy="no-referrer" /> */}
        {/* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/base16/equilibrium-dark.min.css" integrity="sha512-fC5W0x7+liqi1iwL5URfEKrGag2q3pQCjlqERuiZNVbRkeIEyREy5i7zQB1YA2snfD164osH332LBlshcuGrLA==" crossOrigin="anonymous" referrerPolicy="no-referrer" /> */}
        {/* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/base16/equilibrium-gray-dark.min.css" integrity="sha512-wN0TNNUSxgNsFx8SS7XmxSSzbAE+EI/rpqRMUM9aK0DoWel1McANaLp3ItYJwLDHcnZY6tQl6iUatWAJ83Pa4w==" crossOrigin="anonymous" referrerPolicy="no-referrer" /> */}
        {/* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/base16/google-dark.min.css" integrity="sha512-V2tyuo9QXO1DSka4nuMX7wAMMao8h0LQ4cOfDX+I0PkVNiCTwwZ2Ouhh7v7Xirhs/9tKbNMocaGZS6oNuZb/dw==" crossOrigin="anonymous" referrerPolicy="no-referrer" /> */}
        {/* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/base16/humanoid-dark.min.css" integrity="sha512-VpzmzXvIXjYfKE4xjvTjF41gt15bbXf3u0CDWXDm105TA7yphqLSVqAc+gnpJswiS068uRYqiXCC4MvCycjQhg==" crossOrigin="anonymous" referrerPolicy="no-referrer" /> */}
        
        
        
        {/* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.26.0/themes/prism-dark.min.css"></link> */}
        {/* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/prism-themes/1.9.0/prism-material-dark.min.css" integrity="sha512-xkYUyNHum+3ENPH3NP0YcQRYfa3Ocj0jOsRGtcuz3WYVl6YwuVmNpHwiEUrYd7LdMfgbkyt8UvXkoyPVfORS3A==" crossOrigin="anonymous" referrerPolicy="no-referrer" /> */}
        {/* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/prism-themes/1.9.0/prism-gruvbox-dark.min.css" integrity="sha512-XZoe1WroNfbcndQJexn+pbMEytiaSYRHDuKjew+Nn0xYSTmB4sfoZnBdqYCrXq2IwAcPZS/sXE5ju/JbppYOsA==" crossOrigin="anonymous" referrerPolicy="no-referrer" /> */}
        {/* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/prism-themes/1.9.0/prism-vsc-dark-plus.min.css" integrity="sha512-ML8rkwYTFNcblPFx+VLgFIT2boa6f8DDP6p6go4+FT0/mJ8DCbCgi6S0UdjtzB3hKCr1zhU+YVB0AHhIloZP8Q==" crossOrigin="anonymous" referrerPolicy="no-referrer" /> */}
        {/* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/prism-themes/1.9.0/prism-base16-ateliersulphurpool.light.min.css" integrity="sha512-94ZIu7oObnkLRw89FzqulXDU19Kd3IE8oAvOpzhUrQVSPN7n+Ud0MHQA8odjAK964qiEfbncQpgVbdl17qQbQw==" crossOrigin="anonymous" referrerPolicy="no-referrer" /> */}
        {/* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/prism-themes/1.9.0/prism-duotone-earth.min.css" integrity="sha512-BDZ7CTVLQ6MbzkoNiDmsbvBZR8Kngk8RBiuynEl5ENJ9C99XhOypZZ5evynQRUsNoKFUzGWqfrBFumcoNqaCSw==" crossOrigin="anonymous" referrerPolicy="no-referrer" /> */}
        {/* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/prism-themes/1.9.0/prism-shades-of-purple.min.css" integrity="sha512-HM2OlrR8saZI2M4q2qLhGTYpsV8Oh6ktoHraqnYws8D06R7T8a6zIXi/denZBRNxXGHAgpKbIQA3gbz9rQQuuQ==" crossOrigin="anonymous" referrerPolicy="no-referrer" /> */}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.7/dist/katex.min.css" integrity="sha384-3UiQGuEI4TTMaFmGIZumfRPtfKQ3trwQE2JgosJxCnGmQpL/lJdjpcHkaaFwHlcI" crossOrigin="anonymous"></link>
      </head>
      {/* <body className={inter.className}> */}
      {/* <body className="text-slate-950 dark:text-slate-50 dark:bg-stone-800"> */}
      <body className="text-slate-950 dark:text-slate-50 bg-yellow-500">
        <HeaderMain />
        {children}
      </body>
    </html>
  )
}
